version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: ''
        volumes:
            - ./var/mysql:/var/lib/mysql


    app:
        image: webplates/symfony-php:7
        volumes:
            - ./:/app
        working_dir: /app
        links:
            - db
